### Task

In [34]:
def prime_or_not(a):
    c=0
    for i in range(1,a+1):
        if a%i==0:
            c=c+1
    if c==2:
        print("prime")
    else:
         print("not prime")
    

In [35]:
k = int(input())
prime_or_not(k)

3
prime


#### 1st method

In [34]:
def fac_count(a):
    c = 0
    for i in range(1,a+1):
        if a%i==0:
            c=c+1
    return c
        

In [35]:
def isprime(a):
    fc = fac_count(a)
    if fc==2:
        return True
    return False


In [36]:
i = int(input())
if isprime(i):
    print("is prime")
else:
    print("not prime")

3
is prime


In [37]:

def prime_range(lb,ub):
    for i in range(1,100+1):
        if isprime(i):
            print(i,end = ' ')
            


In [38]:
def prime(n):
    if n<2:
        print("not a prime")
    for i in range(2,n//2):
        if n%i==0:
            return False
        return True
    
prime(31)   

True

### Day Objectives:
 * Maps in python
 * Filters in Python
 * Lambdas in Python
 * Numpy2

### Maps

In [51]:
l = list(map(int,['1','2','3','4']))
l

[1, 2, 3, 4]

In [53]:
k=['1','2','3','4']
k

['1', '2', '3', '4']

In [54]:
list(map(int,k))

[1, 2, 3, 4]

In [60]:
i = input().split()

python program


In [67]:
i

['python', 'program']

In [6]:
def addition(n):
    return n+n
addition(5)

10

In [9]:
list(map(addition,[4,7,8,9]))

[8, 14, 16, 18]

In [14]:
def power(n):
    return n**n

In [15]:
list(map(power,[4,7,8,9]))

[256, 823543, 16777216, 387420489]

In [17]:
def sqrt(n):
    return n*n
list(map(sqrt,[1,2,3,4,5]))

[1, 4, 9, 16, 25]

In [21]:
def sqrt(n):
    return n*n
l = list(map(sqrt,[1,2,3,4,5]))
for i in l:
    print(i)

1
4
9
16
25


### Filter

In [25]:
Li = [1,2,'a','b','c',3]
def isDigit(n):
    n = str(n)
    if n.isdigit():
        return True
    return False

list(filter(isDigit,Li))

[1, 2, 3]

In [46]:
Li = [1,2,3,4,5,6,7,8,9,10,11,12,13]
def prime(n):
    if n<2:
        return False
    for i in range(2,n//2+1):
        if n%i==0:
            return False
    return True
    
list(filter(prime,Li))  

[2, 3, 5, 7, 11, 13]

In [31]:
Li = [1,2,3,4,5,6,7,8,9]
def even(n):
    if n%2==0:
        return True
    return False
list(filter(even,Li)) 

[2, 4, 6, 8]

In [32]:
Li = [1,2,3,4,5,6,7,8,9]
def odd(n):
    if n%2!=0:
        return True
    return False
list(filter(odd,Li)) 

[1, 3, 5, 7, 9]

### Lambdas

In [48]:
from random import randint as r
for i in range (1,10+1):
    print(r(1,25))

2
5
1
19
5
3
9
21
9
7


In [54]:
m1 = [r(1,45) for i in range (1,11)]
m2 = [r(1,45) for i in range (1,11)]
m3 = [r(1,45) for i in range (1,11)]
print(m1)
print(m2)
print(m3)

[7, 19, 41, 28, 16, 4, 42, 20, 9, 1]
[23, 6, 41, 9, 31, 4, 29, 29, 13, 6]
[19, 3, 14, 29, 42, 22, 45, 23, 43, 6]


In [57]:
a1 = list(map(lambda x,y:(x+y)//2,m1,m2))
print(a1)

[15, 12, 41, 18, 23, 4, 35, 24, 11, 3]


In [58]:
a2 = list(map(lambda x,y,z:(x+y+z)//3,m1,m2,m3))
print(a2)

[16, 9, 32, 22, 29, 10, 38, 24, 21, 4]


In [65]:
a3 = list(filter(lambda x:x<10,a1))
print(a3)

[4, 3]


In [74]:
list(filter(lambda y:y<10,a2))


[9, 4]

### NumPy

In [76]:
 import numpy as np

In [77]:
l = [1,2,3,4,5]
a1 = np.array(l)
print(a1)

[1 2 3 4 5]


In [78]:
l2 = [[1,2,3],[4,5,6]]
a2=np.array(l2)
print(a2)

[[1 2 3]
 [4 5 6]]


In [80]:
l3 = [[1,2,3],[4,5,6],[7,8,9]]
a3 = np.array(l3)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [93]:
a = np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [99]:
b = np.arange(24).reshape(3,8)
print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [102]:
c=np.arange(6).reshape(2,3)
print(c)

[[0 1 2]
 [3 4 5]]


In [106]:
d1 = np.arange(2,8).reshape(2,3)
d2 = np.arange(22,28).reshape(2,3)
d3 = np.arange(6).reshape(2,3)
print(d1)
print(d2)
print(d3)

[[2 3 4]
 [5 6 7]]
[[22 23 24]
 [25 26 27]]
[[0 1 2]
 [3 4 5]]


In [109]:
d1*d2

array([[ 44,  69,  96],
       [125, 156, 189]])

In [110]:
print(sqrt(d1))

[[ 4  9 16]
 [25 36 49]]


In [111]:
print(np.sin(d1))

[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866 ]]


In [112]:
print(np.shape(d1))

(2, 3)


In [113]:
d1.reshape(3,2)

array([[2, 3],
       [4, 5],
       [6, 7]])

array([[2, 3, 4],
       [5, 6, 7]])